### ISSUE TITLE
Tickets slashing mechanism

### ISSUE THREAD

**Issue by zhaojun-sh** [FUSIONFoundation/efsn#49]
### 1. How to know which blocks retreated tickets?
Run this cmd to grep the imported blocks info from efsn node running log:
`grep Imported nohup.out | grep "order=1"`

> INFO [07-17|15:52:35.196] Imported new chain segment               blocks=1 txs=0   mgas=0.000 elapsed=22.048ms  mgasps=0.000  order=1   number=113519 hash=eaacb0…761839 difficulty=1926 miner=0xe1E31933F1eb215421040998Dc6Ff2C0629a42eF root=f62768…120358 parentHash=bd399e…af6614 time=1563378755   cache=9.63mB

The imported block which **order=1** means that this block was mined by second miner, the order=0 node miss minning this block. Check this block in chaindb:
` ./efsn attach ./data/efsn.ipc --exec "eth.getBlock(113519)"`

In this block, `nonce: "0x0000000000000001"`  same as order=1

> {
>   difficulty: 1926,
>   extraData: "0xd883013e91846566736e88676f312e31322e36856c696e75780000000000000000000a633b08330b3665d03a83d9f69c2131b30f11516e69dc34d7614bdd3f97e220dc33018b70d45ea4294f8f3680a0cee322e8c34ce13e1bb9953761b33275e892fd17e7027f2f547170fb5577656ef0e9912a5d841f92b80fddce0e33b067bd5d4a2659925c705e0c7e4018d9349cca74303856056fed6a13a3514c4c110cde5c02b704b47200",
>   gasLimit: 8000000,
>   gasUsed: 0,
>   hash: "0xeaacb0943abaeedc48405575432ed7055923a72ecca6cb425e85ea5857761839",
>   logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
>   miner: "0xe1e31933f1eb215421040998dc6ff2c0629a42ef",
>   mixHash: "0x0c92fc1e7313715e83227cde7e803dc427bfc54c66e5f943f9efc042aa6ef8d1",
>   nonce: "0x0000000000000001",
>   number: 113519,
>   parentHash: "0xbd399e7a45232eabafdca3cfe546bb4a6bf7ba2f503b9d4b988eba84e5af6614",
>   receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
>   sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
>   size: 682,
>   stateRoot: "0xf62768f7e01fae783bcb0d5770e7f9bdadaaebdf6c0cecd49525aad60b120358",
>   timestamp: 1563378755,
>   totalDifficulty: 288113211,
>   transactions: [],
>   transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
>   uncles: []
> }

**nonce: "0x0000000000000001"** means that this block was mined by second miner, and the order=0 node miss minning this block then it's ticket will be retreated.

`./efsn attach ./data/efsn.ipc --exec "fsn.getSnapshot(web3.toHex("113519"))"`

> {
>   retreat: ["0x8b70d45ea4294f8f3680a0cee322e8c34ce13e1bb9953761b33275e892fd17e7"],
>   selected: "0x3b08330b3665d03a83d9f69c2131b30f11516e69dc34d7614bdd3f97e220dc33",
>   ticketNumber: 2659
> }
> 

### 2. How to know chain forked happened?
Run this cmd to grep the imported blocks info from efsn node running log:
`cat efsnnode.log | grep Imported | grep -Eo "order=0 *number=[0-9]*" | uniq -d | xargs -I{} grep "Imported.*{}" efsnnode.log | tee chainforked.txt`

> INFO [07-17|04:53:01.339] Imported new chain segment               blocks=1 txs=1   mgas=0.022 elapsed=22.682ms  mgasps=0.968  order=0   number=110495 hash=559dc3…0c8b76 difficulty=2926 miner=0x3bfA2C1...778E7F6 root=a17c0e…33ca37 parentHash=32fb1c…9d6cc7 time=1563339168   cache=9.75mB
> INFO [07-17|04:53:02.468] Imported new chain segment               blocks=1 txs=0   mgas=0.000 elapsed=21.586ms  mgasps=0.000  order=0   number=110495 hash=0a96ad…562c24 difficulty=2926 miner=0x3bfA2C1...778E7F6 root=afcc7d…80c2bd parentHash=32fb1c…9d6cc7 time=1563339169   cache=9.81mB

The same node **miner=0x3bfA2C1...778E7F6**, 
the same blocknumber **number=110495** 
the same **parentHash=32fb1c…9d6cc7**.
The three points mean that the miner run two nodes with one wallet, and make the chain forked.

### 3. What is the consensus about Tickets retreated?
The "Tickets Slashing" consensus mechanism improve the stability of the fusion network and prevent attacks.

- Node missed minning block time period, usually the node not online, mined with forked chain, the program interrupted, or the network problem, etc. The ticket will be retreated.(deployed)
- "double-blocking": Miner run more than one node with one wallet address and broadcast more than one block at the same block height. The node will be slashed at least two tickets, depending on how many blocks are duplicated.(next update)

Nodes in the network can report the "double-blocking" behavior, submit a special transaction which list the evidence, and the "Ticket Slashing" consensus mechanism will punish the attack node, slash at least two tickets.

**Comment by Iruwen** [comment]
I like the term "double-blocking" :-) Approach sounds solid.

Following up on this reasoning:

A malicious miner broadcasts multiple blocks to the network. There's consensus that this is an offense. The miner gets punished. Still, he'll create forks until he runs out of tickets. The "double-blocking" punishment makes it less likely, but it might simply be an unknowing or ignorant miner, a troll or a failing failover mechanism (hot spare starts mining).

A benevolent miner broadcasts a block to the network too, which unfortunately is a descendant of a block created by aforementioned malicious miner. It never reaches the canonical chain, so this miner gets punished as well.

Question: can't blocks broadcast by the benevolent miner with good intentions (afaik on Ethereum, uncle blocks are even rewarded) be recognized too as such by the network, and the punishment automatically be reversed on the consensus level in that case? I mean this is different from a node actually being offline, where no blocks are broadcast at all.

An even more effective approach would be to transfer the time-locked FSN contained in a retreated ticket from the malicious miner to the benevolent miner, which would have two strong effects:
1) the punishment turns from just losing 30 days of staking to actually giving someone else 30 days of staking, which stops trolls.
2) retreated tickets are redistributed to the network randomly, keeping its total weight stable, as opposed to completely losing a considerable part of the tickets in case of an unforseeable incident (like a major pool being affected by some super unfortunate connectivity-related edge case).

**Comment by cross-chain** [comment]
1. about double-blocking
Only a `same miner` mine two blocks base on a `same parent block` is treated as double-blocking and gets punished. mining on forked branching blocks should have `different parent block` and will not be treated as double-blocking.
Punish double-blocking aims to decrease chain forks, so punishment is enough to prevent double-blocking. no need to award the reporter  to encourage them dive into blockchain unrelated functions.

2. about retreated tickets
Only the `first ordered` (order=0) miner misses his turn to create a new block will get punished(delete that ticket and won't return his time-lock balance used to buy this ticket).
Punishing miners not create blocks in time will lead them maitain their nodes more stable.
Block mined not by the first ordered miner situation should happen not frequently. When double-blocking is prevented, this situation will become lesser to happen.
Otherwise, if award the miner (order>0) under this situation, it may lead to more people want to attack the first ordered miners to prevent him to mine normally and get the awards. this is a bad incentives which make the blockchain becomes less stable.
