### ISSUE TITLE
[BUG]UDP package reflection vulnerability in p2p/discover/udp.go

### ISSUE THREAD

**Issue by qiushui777** [FUSIONFoundation/efsn#51]
**Brief introduction:**
In p2p/discover/udp.go, there is is a well-known vulnerability from Etheruem. As you are using the code from Ethereum and haven't updated the code, your code has the same problem here. The problem is in the function `func (t *udp) loop()`. 
In the case `case r := <-t.gotreply:`, the code is
`if p.callback(r.data) {
						p.errc <- nil
						plist.Remove(el)
}`
Here, even the p.callback has something wrong , it won't change the matched flag. The matched flag is used to contain the hash of the previous ping package. This means even if the hash doesn't match, it won't give the error and will always accept the connection. If you guys know the protocol, you will know I can give you the target node ip, and require the "find neighbors" and the reflect all the traffic to the target node. This can lead to a serious DDOS attack.

`Expected behaviour/How to patch`

You can check the code of  here ,
https://github.com/simplechain-org/simplechain/blob/master/p2p/discover/udp.go#L453
This project use the same code but update the corresponding codes. You need do change the matched flag if the hash won't match. You can sync the code of the corresponding version of etherum. 

By the way, if you can read chinese, in order to make your life easier, this link will be helpful in helping you understanding the harm of this vulnerability.
https://bcsec.org/index/detail/tag/2/id/489

`step to reproduce the behavior`

1. get a fake udp source address
2.send a ping to udp port with the fake ip
3. send a pong to the udp port with empty hash
4. send findnode pacakge to reflect 5 times traffic

As I said , you can always check the link above to see the harm. They have pictures there.

**Comment by qiushui777** [comment]
By the way, I can't send to email to the reward address rewards@fusion.org . It keeps give me error saying that you are rejecting my email. Can you give another email for contacting?

**Comment by zhaojun-sh** [comment]
@qiushui777  Thanks for vulnerability info.  You can connect me.

**Comment by qiushui777** [comment]
@zhaojun-sh thanks for your reply. I emailed you yesterday.

**Comment by JoeyKhd** [comment]
Could you please close the issue once it has been resolved. @zhaojun-sh Thank you!
