### ISSUE TITLE
Is there any relationship between efsn and dcrm-go-mvp?

### ISSUE THREAD

**Issue by nkbai** [FUSIONFoundation/efsn#54]
I cannot find any usage of dcrm-go-mvp in this project.
can some one give me some tips of the usage of dcrm?

**Comment by nycat** [comment]
> I cannot find any usage of dcrm-go-mvp in this project.
> can some one give me some tips of the usage of dcrm?

https://github.com/fsn-dev/dcrm-sdk

**Comment by nkbai** [comment]
doesn't project efsn  use dcrm?

**Comment by nycat** [comment]
> doesn't project efsn use dcrm?

I guess EFSN will DCRM in the near future. You can also join our Wechat dev community if you are Chinese. Or Join us at the telegram dev community via https://t.me/FsnDevCommunity.
