### ISSUE TITLE
AWS setup guide creates low storage instance

### ISSUE THREAD

**Issue by Iruwen** [FUSIONFoundation/efsn#60]
The official guide
https://medium.com/@fusionprotocol/how-to-set-up-a-fusion-node-part-3-how-to-set-up-a-vps-on-aws-36917ec58bc3
still contains a link to an old fsn.yml
https://fusion-org-public.s3.us-east-2.amazonaws.com/fsn.yml
instead of the fixed one
https://raw.githubusercontent.com/FUSIONFoundation/efsn/master/QuickNodeSetup/fsn.yml
See https://github.com/FUSIONFoundation/efsn/pull/52

**Comment by zhaojun-sh** [comment]
Fixed.

**Comment by Iruwen** [comment]
Thanks.
