### ISSUE TITLE
No data returned for method  `fsn_getBalance` with rpc service

### ISSUE THREAD

**Issue by katesroad** [FUSIONFoundation/efsn#61]
I called  the RPC service provider https://fsn.dev/api  by replacing the address params in [example](https://github.com/FUSIONFoundation/efsn/wiki/FSN-RPC-API#fsn_getBalance) with *0x76c2ae4281fe1ee1a79ccbdda2516d4d7eb0eb37* 

The returned data from the RPC service is a blank string ‘’. 

**Looks like other methods have the same issue.**
@zhaojun-sh  @Iruwen

**Comment by cross-chain** [comment]
Please give us your concrete request and response, thank you!

I have tried the following, but found no problem:
```js
// request
curl -X POST -H "Content-Type":application/json --data '{"jsonrpc":"2.0","method":"fsn_getBalance","params":["0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff","0x76c2ae4281fe1ee1a79ccbdda2516d4d7eb0eb37","latest"],"id":1}' https://fsn.dev/api

// response
{"jsonrpc":"2.0","id":1,"result":"810074950109653466317"}
```
