### ISSUE TITLE
High number of transactions causing node outages and network reorgs/stalls

### ISSUE THREAD

**Issue by Iruwen** [FUSIONFoundation/efsn#66]
A very high amount of transactions leads to the occasional network stalling we see, eventually due to efsn oom crashes or maybe there's some other issue involved causing problems with the ticket selection.

Wedefi started its daily mass txs with block 2627672 tonight, at 01:34 UTC:

https://fsnex.com/block/2627672

This is what my system monitoring shows starting at that time - notice the increasing memory usage, suddenly hitting a cliff:

![image](https://user-images.githubusercontent.com/11341130/89120970-0f5dcd80-d4bb-11ea-9346-1e12de4b7153.png)

My node struggles with sharply increasing memory and CPU usage as Wedefi keeps pushing, but eventually keeps working until it finally dies at ~02:05 UTC, followed by a manual reboot.

Here's some relevant excerpts from my logs:

01:34 UTC:

![image](https://user-images.githubusercontent.com/11341130/89121700-62d31a00-d4c1-11ea-9538-e01805539648.png)

01:39 UTC:

![image](https://user-images.githubusercontent.com/11341130/89121717-9f067a80-d4c1-11ea-8599-cceee440c151.png)

01:43 UTC:

![image](https://user-images.githubusercontent.com/11341130/89121722-aded2d00-d4c1-11ea-86a6-043f87cf60b1.png)

01:47 UTC:

![image](https://user-images.githubusercontent.com/11341130/89121730-ba718580-d4c1-11ea-91ef-a41a7ad45dd5.png)

01:48 UTC, the network just keeps degrading:

![image](https://user-images.githubusercontent.com/11341130/89121739-cd845580-d4c1-11ea-8cb0-ca5eef4d6db0.png)

Starting 02:02 UTC, my node capitulates and my monitoring triggers a critical alert:

![image](https://user-images.githubusercontent.com/11341130/89121760-ff95b780-d4c1-11ea-88e0-829a269f04ad.png)

![image](https://user-images.githubusercontent.com/11341130/89121764-0e7c6a00-d4c2-11ea-939e-afe641ab5f05.png)

Around the same time, Krypton noticed in the dev channel that the network is in a degraded state. It started recovering after, with a few nodes failing to catch up until some time later.

**Comment by zhaojun-sh** [comment]
The TL transactions need more resources, this part needs to be optimized.

**Comment by zhaojun-sh** [comment]
limit timelock transactions count mined in a block.  https://github.com/FUSIONFoundation/efsn/commit/32f7784913dafe3899053fa5c1f4d108e3f8fa92
