### ISSUE TITLE
Ticket retreated for no reason

### ISSUE THREAD

**Issue by Iruwen** [FUSIONFoundation/efsn#67]
I just had a ticket retreated for absolutely no reason. The node said "mining too far in the future" at the time.

Ticket id: 0x027411e798a112c55698a7ef758cc2fe6ea2ce68ee1b5e2e8207cbc7913c26c4
Purchased in block: 2653202
Retreated in block: 2657537.

![image](https://user-images.githubusercontent.com/11341130/89548031-ced9b900-d806-11ea-90ba-554cd93845d6.png)

The node was connected and mining normally the whole time as per my external monitoring.

No deviation from the expected height:

![image](https://user-images.githubusercontent.com/11341130/89547961-b36eae00-d806-11ea-97ed-e8c4c05f2eaa.png)

Not fallen behind (eth.syncing was never true):

![image](https://user-images.githubusercontent.com/11341130/89548110-e7e26a00-d806-11ea-906c-ee826340eb3c.png)

Number of tickets drops:

![image](https://user-images.githubusercontent.com/11341130/89548388-44458980-d807-11ea-9f9d-2d4bcbbbbb56.png)

**Comment by Krypton-Kr** [comment]
Having similar issues.  Node looks good.  Tickets just retreat.  Only message indicated in logs: "Mining too far in the future".  Machine clock is in sync; so, anomalies from my end.  Something out there is causing periodic network lag.  I can rule out my hardware; since my specs are top-notch.  Besides, my node fared very well during the last two reorgs. My main node vps is a dedicated server with the following:  

     * Intel Xeon E3-1275V6
     * 2x SSD SATA 480 GB Datacenter (960 GB total)
     * 4x RAM 16384 MB DDR4 ECC (64 GB total)
     * NIC: 1 Gbit - Intel I219-LM

**Comment by zhaojun-sh** [comment]
@Krypton-Kr  Please put the log details. Thanks.

**Comment by Krypton-Kr** [comment]
I'm pm'ing you the complete log in TG (it's very large ~ 54MB)...  Please let me know once you've received it. Thanks!

**Comment by Krypton-Kr** [comment]
@zhaojun-sh  OK - The log uploaded to you successfully.  Please check DM in telegram.  Let me know if you have what you need.

**Comment by zhaojun-sh** [comment]
Fixed. https://github.com/FUSIONFoundation/efsn/commit/2c69a8784012c9f5d1546c747b0c31b5bb1fceef
