### ISSUE TITLE
Bug bounty

### ISSUE THREAD

**Issue by akincibor** [FUSIONFoundation/efsn#68]
Hi,

I was searching for vulnerability because of your program here https://www.fusion.org/en/developers/bug-bounty and I found a critical vulnerability but since 3 months I'm trying to contact you via email but no answer I send also an email to @khaneight when I see that he is working as a dev. But no answer so how to contact you ? @JoeyKhd ?

Best,
Akincibor

**Comment by individualpirate** [comment]
Contact @fanbsb

**Comment by akincibor** [comment]
How to contact him lol

**Comment by fanbsb** [comment]
my email wengang.fan@chainge.finance

**Comment by fanbsb** [comment]
not a bug, it's deprecated repo, closed

**Comment by akincibor** [comment]
It was a dependency confusion in an old repo. No bounty received !
